// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package reply

import (
	"context"

	"rpc-social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminReplyListRequest  = social.AdminReplyListRequest
	AdminReplyListResponse = social.AdminReplyListResponse
	CreateReplyRequest     = social.CreateReplyRequest
	CreateReplyResponse    = social.CreateReplyResponse
	DeleteReplyRequest     = social.DeleteReplyRequest
	DeleteReplyResponse    = social.DeleteReplyResponse
	ReplyCountRequest      = social.ReplyCountRequest
	ReplyCountResponse     = social.ReplyCountResponse
	ReplyDetailRequest     = social.ReplyDetailRequest
	ReplyDetailResponse    = social.ReplyDetailResponse
	ReplyListRequest       = social.ReplyListRequest
	ReplyListResponse      = social.ReplyListResponse

	Reply interface {
		CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error)
		DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error)
		ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error)
		ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error)
		ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error)
		AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.CreateReply(ctx, in, opts...)
}

func (m *defaultReply) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.DeleteReply(ctx, in, opts...)
}

func (m *defaultReply) ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.ReplyDetail(ctx, in, opts...)
}

func (m *defaultReply) ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.ReplyList(ctx, in, opts...)
}

func (m *defaultReply) ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.ReplyCount(ctx, in, opts...)
}

func (m *defaultReply) AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error) {
	client := social.NewReplyClient(m.cli.Conn())
	return client.AdminReplyList(ctx, in, opts...)
}
