// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"rpc-social/internal/logic/chat"
	"rpc-social/internal/svc"
	"rpc-social/social"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) SendMessage(ctx context.Context, in *social.SendMessageRequest) (*social.SendMessageResponse, error) {
	l := chatlogic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *ChatServer) Conversations(ctx context.Context, in *social.ConversationsRequest) (*social.ConversationsResponse, error) {
	l := chatlogic.NewConversationsLogic(ctx, s.svcCtx)
	return l.Conversations(in)
}

func (s *ChatServer) Messages(ctx context.Context, in *social.MessagesRequest) (*social.MessagesResponse, error) {
	l := chatlogic.NewMessagesLogic(ctx, s.svcCtx)
	return l.Messages(in)
}

func (s *ChatServer) MarkRead(ctx context.Context, in *social.ChatMarkReadRequest) (*social.ChatMarkReadResponse, error) {
	l := chatlogic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}

func (s *ChatServer) UnreadCount(ctx context.Context, in *social.ChatUnreadCountRequest) (*social.ChatUnreadCountResponse, error) {
	l := chatlogic.NewUnreadCountLogic(ctx, s.svcCtx)
	return l.UnreadCount(in)
}
