services:
  rpc-social:
    build:
      context: .
      dockerfile: Dockerfile
    image: rpc-social:latest
    container_name: rpc-social
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./etc:/app/etc
    environment:
      - ETCD_ENDPOINTS=10.8.0.1:2379
    networks:
      - thinktalk-net

networks:
  thinktalk-net:
    driver: bridge
