// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"rpc-social/internal/logic/message"
	"rpc-social/internal/svc"
	"rpc-social/social"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) NotificationList(ctx context.Context, in *social.NotificationListRequest) (*social.NotificationListResponse, error) {
	l := messagelogic.NewNotificationListLogic(ctx, s.svcCtx)
	return l.NotificationList(in)
}

func (s *MessageServer) UnreadCount(ctx context.Context, in *social.UnreadCountRequest) (*social.UnreadCountResponse, error) {
	l := messagelogic.NewUnreadCountLogic(ctx, s.svcCtx)
	return l.UnreadCount(in)
}

func (s *MessageServer) MarkRead(ctx context.Context, in *social.MarkReadRequest) (*social.MarkReadResponse, error) {
	l := messagelogic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}

func (s *MessageServer) MarkAllRead(ctx context.Context, in *social.MarkAllReadRequest) (*social.MarkAllReadResponse, error) {
	l := messagelogic.NewMarkAllReadLogic(ctx, s.svcCtx)
	return l.MarkAllRead(in)
}

func (s *MessageServer) DeleteNotification(ctx context.Context, in *social.DeleteNotificationRequest) (*social.DeleteNotificationResponse, error) {
	l := messagelogic.NewDeleteNotificationLogic(ctx, s.svcCtx)
	return l.DeleteNotification(in)
}
