// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"rpc-social/internal/logic/reply"
	"rpc-social/internal/svc"
	"rpc-social/social"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) CreateReply(ctx context.Context, in *social.CreateReplyRequest) (*social.CreateReplyResponse, error) {
	l := replylogic.NewCreateReplyLogic(ctx, s.svcCtx)
	return l.CreateReply(in)
}

func (s *ReplyServer) DeleteReply(ctx context.Context, in *social.DeleteReplyRequest) (*social.DeleteReplyResponse, error) {
	l := replylogic.NewDeleteReplyLogic(ctx, s.svcCtx)
	return l.DeleteReply(in)
}

func (s *ReplyServer) ReplyDetail(ctx context.Context, in *social.ReplyDetailRequest) (*social.ReplyDetailResponse, error) {
	l := replylogic.NewReplyDetailLogic(ctx, s.svcCtx)
	return l.ReplyDetail(in)
}

func (s *ReplyServer) ReplyList(ctx context.Context, in *social.ReplyListRequest) (*social.ReplyListResponse, error) {
	l := replylogic.NewReplyListLogic(ctx, s.svcCtx)
	return l.ReplyList(in)
}

func (s *ReplyServer) ReplyCount(ctx context.Context, in *social.ReplyCountRequest) (*social.ReplyCountResponse, error) {
	l := replylogic.NewReplyCountLogic(ctx, s.svcCtx)
	return l.ReplyCount(in)
}

func (s *ReplyServer) AdminReplyList(ctx context.Context, in *social.AdminReplyListRequest) (*social.AdminReplyListResponse, error) {
	l := replylogic.NewAdminReplyListLogic(ctx, s.svcCtx)
	return l.AdminReplyList(in)
}
