// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package chat

import (
	"context"

	"rpc-social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatMarkReadRequest     = social.ChatMarkReadRequest
	ChatMarkReadResponse    = social.ChatMarkReadResponse
	ChatUnreadCountRequest  = social.ChatUnreadCountRequest
	ChatUnreadCountResponse = social.ChatUnreadCountResponse
	ConversationsRequest    = social.ConversationsRequest
	ConversationsResponse   = social.ConversationsResponse
	MessagesRequest         = social.MessagesRequest
	MessagesResponse        = social.MessagesResponse
	SendMessageRequest      = social.SendMessageRequest
	SendMessageResponse     = social.SendMessageResponse

	Chat interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		Conversations(ctx context.Context, in *ConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error)
		Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
		MarkRead(ctx context.Context, in *ChatMarkReadRequest, opts ...grpc.CallOption) (*ChatMarkReadResponse, error)
		UnreadCount(ctx context.Context, in *ChatUnreadCountRequest, opts ...grpc.CallOption) (*ChatUnreadCountResponse, error)
	}

	defaultChat struct {
		cli zrpc.Client
	}
)

func NewChat(cli zrpc.Client) Chat {
	return &defaultChat{
		cli: cli,
	}
}

func (m *defaultChat) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := social.NewChatClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultChat) Conversations(ctx context.Context, in *ConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error) {
	client := social.NewChatClient(m.cli.Conn())
	return client.Conversations(ctx, in, opts...)
}

func (m *defaultChat) Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	client := social.NewChatClient(m.cli.Conn())
	return client.Messages(ctx, in, opts...)
}

func (m *defaultChat) MarkRead(ctx context.Context, in *ChatMarkReadRequest, opts ...grpc.CallOption) (*ChatMarkReadResponse, error) {
	client := social.NewChatClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

func (m *defaultChat) UnreadCount(ctx context.Context, in *ChatUnreadCountRequest, opts ...grpc.CallOption) (*ChatUnreadCountResponse, error) {
	client := social.NewChatClient(m.cli.Conn())
	return client.UnreadCount(ctx, in, opts...)
}
