// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"rpc-social/internal/logic/like"
	"rpc-social/internal/svc"
	"rpc-social/social"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Thumbup(ctx context.Context, in *social.ThumbupRequest) (*social.ThumbupResponse, error) {
	l := likelogic.NewThumbupLogic(ctx, s.svcCtx)
	return l.Thumbup(in)
}

func (s *LikeServer) IsThumbup(ctx context.Context, in *social.IsThumbupRequest) (*social.IsThumbupResponse, error) {
	l := likelogic.NewIsThumbupLogic(ctx, s.svcCtx)
	return l.IsThumbup(in)
}
