// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package concerned

import (
	"context"

	"rpc-social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddConcernedRequest     = social.AddConcernedRequest
	AddConcernedResponse    = social.AddConcernedResponse
	CancelConcernedRequest  = social.CancelConcernedRequest
	CancelConcernedResponse = social.CancelConcernedResponse
	ConcernedCountRequest   = social.ConcernedCountRequest
	ConcernedCountResponse  = social.ConcernedCountResponse
	ConcernedListRequest    = social.ConcernedListRequest
	ConcernedListResponse   = social.ConcernedListResponse
	IsConcernedRequest      = social.IsConcernedRequest
	IsConcernedResponse     = social.IsConcernedResponse

	Concerned interface {
		AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error)
		CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error)
		IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error)
		ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error)
		ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error)
	}

	defaultConcerned struct {
		cli zrpc.Client
	}
)

func NewConcerned(cli zrpc.Client) Concerned {
	return &defaultConcerned{
		cli: cli,
	}
}

func (m *defaultConcerned) AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error) {
	client := social.NewConcernedClient(m.cli.Conn())
	return client.AddConcerned(ctx, in, opts...)
}

func (m *defaultConcerned) CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error) {
	client := social.NewConcernedClient(m.cli.Conn())
	return client.CancelConcerned(ctx, in, opts...)
}

func (m *defaultConcerned) IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error) {
	client := social.NewConcernedClient(m.cli.Conn())
	return client.IsConcerned(ctx, in, opts...)
}

func (m *defaultConcerned) ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error) {
	client := social.NewConcernedClient(m.cli.Conn())
	return client.ConcernedList(ctx, in, opts...)
}

func (m *defaultConcerned) ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error) {
	client := social.NewConcernedClient(m.cli.Conn())
	return client.ConcernedCount(ctx, in, opts...)
}
