syntax = "proto3";

package social;
option go_package = "api-thinktalk/client/concerned/pb;pb";

service Concerned {
  rpc AddConcerned(AddConcernedRequest) returns (AddConcernedResponse);
  rpc CancelConcerned(CancelConcernedRequest) returns (CancelConcernedResponse);
  rpc IsConcerned(IsConcernedRequest) returns (IsConcernedResponse);
  rpc ConcernedList(ConcernedListRequest) returns (ConcernedListResponse);
  rpc ConcernedCount(ConcernedCountRequest) returns (ConcernedCountResponse);
}

message AddConcernedRequest {
  string bizId = 1;
  int64 objId = 2;
  int64 userId = 3;
}

message AddConcernedResponse {
  int64 code = 1;
  string msg = 2;
}

message CancelConcernedRequest {
  string bizId = 1;
  int64 objId = 2;
  int64 userId = 3;
}

message CancelConcernedResponse {
  int64 code = 1;
  string msg = 2;
}

message IsConcernedRequest {
  string bizId = 1;
  int64 objId = 2;
  int64 userId = 3;
}

message IsConcernedData {
  bool isConcerned = 1;
}

message IsConcernedResponse {
  int64 code = 1;
  string msg = 2;
  IsConcernedData data = 3;
}

message ConcernedListRequest {
  int64 userId = 1;
  string bizId = 2;
  int64 cursor = 3;
  int64 pageSize = 4;
}

message ConcernedItem {
  int64 id = 1;
  string bizId = 2;
  int64 objId = 3;
  int64 createTime = 4;
}

message ConcernedListData {
  repeated ConcernedItem items = 1;
  int64 cursor = 2;
  bool isEnd = 3;
}

message ConcernedListResponse {
  int64 code = 1;
  string msg = 2;
  ConcernedListData data = 3;
}

message ConcernedCountRequest {
  string bizId = 1;
  int64 objId = 2;
}

message ConcernedCountData {
  int64 concernedNum = 1;
}

message ConcernedCountResponse {
  int64 code = 1;
  string msg = 2;
  ConcernedCountData data = 3;
}
