syntax = "proto3";

package social;
option go_package = "api-thinktalk/client/reply/pb;pb";

service Reply {
  rpc CreateReply(CreateReplyRequest) returns (CreateReplyResponse);
  rpc DeleteReply(DeleteReplyRequest) returns (DeleteReplyResponse);
  rpc ReplyDetail(ReplyDetailRequest) returns (ReplyDetailResponse);
  rpc ReplyList(ReplyListRequest) returns (ReplyListResponse);
  rpc ReplyCount(ReplyCountRequest) returns (ReplyCountResponse);
  rpc AdminReplyList(AdminReplyListRequest) returns (AdminReplyListResponse);
}

message CreateReplyRequest {
  string bizId = 1;
  int64 targetId = 2;
  int64 replyUserId = 3;
  int64 beReplyUserId = 4;
  int64 parentId = 5;
  string content = 6;
}

message CreateReplyData {
  int64 replyId = 1;
}

message CreateReplyResponse {
  int64 code = 1;
  string msg = 2;
  CreateReplyData data = 3;
}

message DeleteReplyRequest {
  int64 replyId = 1;
  int64 userId = 2;
  bool isAdmin = 3;
}

message DeleteReplyResponse {
  int64 code = 1;
  string msg = 2;
}

message ReplyDetailRequest {
  int64 replyId = 1;
}

message ReplyItem {
  int64 replyId = 1;
  string bizId = 2;
  int64 targetId = 3;
  int64 replyUserId = 4;
  int64 beReplyUserId = 5;
  int64 parentId = 6;
  string content = 7;
  int64 likeNum = 8;
  int64 createTime = 9;
  repeated ReplyItem subReplies = 10;
}

message ReplyDetailResponse {
  int64 code = 1;
  string msg = 2;
  ReplyItem data = 3;
}

message ReplyListRequest {
  string bizId = 1;
  int64 targetId = 2;
  int64 cursor = 3;
  int64 pageSize = 4;
  int32 sortType = 5;
}

message ReplyListData {
  repeated ReplyItem items = 1;
  int64 cursor = 2;
  bool isEnd = 3;
}

message ReplyListResponse {
  int64 code = 1;
  string msg = 2;
  ReplyListData data = 3;
}

message ReplyCountRequest {
  string bizId = 1;
  int64 targetId = 2;
}

message ReplyCountData {
  int64 replyNum = 1;
  int64 replyRootNum = 2;
}

message ReplyCountResponse {
  int64 code = 1;
  string msg = 2;
  ReplyCountData data = 3;
}

message AdminReplyListRequest {
  string keyword = 1;
  int64 cursor = 2;
  int64 pageSize = 3;
}

message AdminReplyListResponse {
  int64 code = 1;
  string msg = 2;
  ReplyListData data = 3;
}
