// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package message

import (
	"context"

	"rpc-social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteNotificationRequest  = social.DeleteNotificationRequest
	DeleteNotificationResponse = social.DeleteNotificationResponse
	MarkAllReadRequest         = social.MarkAllReadRequest
	MarkAllReadResponse        = social.MarkAllReadResponse
	MarkReadRequest            = social.MarkReadRequest
	MarkReadResponse           = social.MarkReadResponse
	NotificationListRequest    = social.NotificationListRequest
	NotificationListResponse   = social.NotificationListResponse
	UnreadCountRequest         = social.UnreadCountRequest
	UnreadCountResponse        = social.UnreadCountResponse

	Message interface {
		NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error)
		UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*UnreadCountResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
		MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
		DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error) {
	client := social.NewMessageClient(m.cli.Conn())
	return client.NotificationList(ctx, in, opts...)
}

func (m *defaultMessage) UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*UnreadCountResponse, error) {
	client := social.NewMessageClient(m.cli.Conn())
	return client.UnreadCount(ctx, in, opts...)
}

func (m *defaultMessage) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := social.NewMessageClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

func (m *defaultMessage) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	client := social.NewMessageClient(m.cli.Conn())
	return client.MarkAllRead(ctx, in, opts...)
}

func (m *defaultMessage) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	client := social.NewMessageClient(m.cli.Conn())
	return client.DeleteNotification(ctx, in, opts...)
}
