// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package like

import (
	"context"

	"rpc-social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsThumbupRequest  = social.IsThumbupRequest
	IsThumbupResponse = social.IsThumbupResponse
	ThumbupRequest    = social.ThumbupRequest
	ThumbupResponse   = social.ThumbupResponse

	Like interface {
		Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error)
		IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error) {
	client := social.NewLikeClient(m.cli.Conn())
	return client.Thumbup(ctx, in, opts...)
}

func (m *defaultLike) IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error) {
	client := social.NewLikeClient(m.cli.Conn())
	return client.IsThumbup(ctx, in, opts...)
}
