// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: reply.proto

package reply

import (
	"context"

	"rpc-social/reply/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReplyRequest  = pb.CreateReplyRequest
	CreateReplyResponse = pb.CreateReplyResponse
	DeleteReplyRequest  = pb.DeleteReplyRequest
	DeleteReplyResponse = pb.DeleteReplyResponse
	ReplyCountRequest   = pb.ReplyCountRequest
	ReplyCountResponse  = pb.ReplyCountResponse
	ReplyDetailRequest  = pb.ReplyDetailRequest
	ReplyDetailResponse = pb.ReplyDetailResponse
	ReplyItem           = pb.ReplyItem
	ReplyListRequest        = pb.ReplyListRequest
	ReplyListResponse       = pb.ReplyListResponse
	AdminReplyListRequest   = pb.AdminReplyListRequest
	AdminReplyListResponse  = pb.AdminReplyListResponse

	Reply interface {
		// 发表评论
		CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error)
		// 删除评论
		DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error)
		// 评论详情
		ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error)
		// 评论列表
		ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error)
		// 评论计数
		ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error)
		// 管理员评论列表
		AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

// 发表评论
func (m *defaultReply) CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.CreateReply(ctx, in, opts...)
}

// 删除评论
func (m *defaultReply) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.DeleteReply(ctx, in, opts...)
}

// 评论详情
func (m *defaultReply) ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.ReplyDetail(ctx, in, opts...)
}

// 评论列表
func (m *defaultReply) ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.ReplyList(ctx, in, opts...)
}

// 评论计数
func (m *defaultReply) ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.ReplyCount(ctx, in, opts...)
}

func (m *defaultReply) AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error) {
	client := pb.NewReplyClient(m.cli.Conn())
	return client.AdminReplyList(ctx, in, opts...)
}
