// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Like_Thumbup_FullMethodName   = "/social.Like/Thumbup"
	Like_IsThumbup_FullMethodName = "/social.Like/IsThumbup"
)

// LikeClient is the client API for Like service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 点赞服务 -----------------------------
type LikeClient interface {
	Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error)
	IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error)
}

type likeClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeClient(cc grpc.ClientConnInterface) LikeClient {
	return &likeClient{cc}
}

func (c *likeClient) Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThumbupResponse)
	err := c.cc.Invoke(ctx, Like_Thumbup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsThumbupResponse)
	err := c.cc.Invoke(ctx, Like_IsThumbup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServer is the server API for Like service.
// All implementations must embed UnimplementedLikeServer
// for forward compatibility.
//
// --------------------------- 点赞服务 -----------------------------
type LikeServer interface {
	Thumbup(context.Context, *ThumbupRequest) (*ThumbupResponse, error)
	IsThumbup(context.Context, *IsThumbupRequest) (*IsThumbupResponse, error)
	mustEmbedUnimplementedLikeServer()
}

// UnimplementedLikeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikeServer struct{}

func (UnimplementedLikeServer) Thumbup(context.Context, *ThumbupRequest) (*ThumbupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Thumbup not implemented")
}
func (UnimplementedLikeServer) IsThumbup(context.Context, *IsThumbupRequest) (*IsThumbupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsThumbup not implemented")
}
func (UnimplementedLikeServer) mustEmbedUnimplementedLikeServer() {}
func (UnimplementedLikeServer) testEmbeddedByValue()              {}

// UnsafeLikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServer will
// result in compilation errors.
type UnsafeLikeServer interface {
	mustEmbedUnimplementedLikeServer()
}

func RegisterLikeServer(s grpc.ServiceRegistrar, srv LikeServer) {
	// If the following call panics, it indicates UnimplementedLikeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Like_ServiceDesc, srv)
}

func _Like_Thumbup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).Thumbup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Thumbup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).Thumbup(ctx, req.(*ThumbupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_IsThumbup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsThumbupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).IsThumbup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_IsThumbup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).IsThumbup(ctx, req.(*IsThumbupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_ServiceDesc is the grpc.ServiceDesc for Like service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Like",
	HandlerType: (*LikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Thumbup",
			Handler:    _Like_Thumbup_Handler,
		},
		{
			MethodName: "IsThumbup",
			Handler:    _Like_IsThumbup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}

const (
	Concerned_AddConcerned_FullMethodName    = "/social.Concerned/AddConcerned"
	Concerned_CancelConcerned_FullMethodName = "/social.Concerned/CancelConcerned"
	Concerned_IsConcerned_FullMethodName     = "/social.Concerned/IsConcerned"
	Concerned_ConcernedList_FullMethodName   = "/social.Concerned/ConcernedList"
	Concerned_ConcernedCount_FullMethodName  = "/social.Concerned/ConcernedCount"
)

// ConcernedClient is the client API for Concerned service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 收藏服务 -----------------------------
type ConcernedClient interface {
	AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error)
	CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error)
	IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error)
	ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error)
	ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error)
}

type concernedClient struct {
	cc grpc.ClientConnInterface
}

func NewConcernedClient(cc grpc.ClientConnInterface) ConcernedClient {
	return &concernedClient{cc}
}

func (c *concernedClient) AddConcerned(ctx context.Context, in *AddConcernedRequest, opts ...grpc.CallOption) (*AddConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_AddConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) CancelConcerned(ctx context.Context, in *CancelConcernedRequest, opts ...grpc.CallOption) (*CancelConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_CancelConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) IsConcerned(ctx context.Context, in *IsConcernedRequest, opts ...grpc.CallOption) (*IsConcernedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsConcernedResponse)
	err := c.cc.Invoke(ctx, Concerned_IsConcerned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) ConcernedList(ctx context.Context, in *ConcernedListRequest, opts ...grpc.CallOption) (*ConcernedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcernedListResponse)
	err := c.cc.Invoke(ctx, Concerned_ConcernedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *concernedClient) ConcernedCount(ctx context.Context, in *ConcernedCountRequest, opts ...grpc.CallOption) (*ConcernedCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcernedCountResponse)
	err := c.cc.Invoke(ctx, Concerned_ConcernedCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConcernedServer is the server API for Concerned service.
// All implementations must embed UnimplementedConcernedServer
// for forward compatibility.
//
// --------------------------- 收藏服务 -----------------------------
type ConcernedServer interface {
	AddConcerned(context.Context, *AddConcernedRequest) (*AddConcernedResponse, error)
	CancelConcerned(context.Context, *CancelConcernedRequest) (*CancelConcernedResponse, error)
	IsConcerned(context.Context, *IsConcernedRequest) (*IsConcernedResponse, error)
	ConcernedList(context.Context, *ConcernedListRequest) (*ConcernedListResponse, error)
	ConcernedCount(context.Context, *ConcernedCountRequest) (*ConcernedCountResponse, error)
	mustEmbedUnimplementedConcernedServer()
}

// UnimplementedConcernedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConcernedServer struct{}

func (UnimplementedConcernedServer) AddConcerned(context.Context, *AddConcernedRequest) (*AddConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddConcerned not implemented")
}
func (UnimplementedConcernedServer) CancelConcerned(context.Context, *CancelConcernedRequest) (*CancelConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelConcerned not implemented")
}
func (UnimplementedConcernedServer) IsConcerned(context.Context, *IsConcernedRequest) (*IsConcernedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsConcerned not implemented")
}
func (UnimplementedConcernedServer) ConcernedList(context.Context, *ConcernedListRequest) (*ConcernedListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConcernedList not implemented")
}
func (UnimplementedConcernedServer) ConcernedCount(context.Context, *ConcernedCountRequest) (*ConcernedCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConcernedCount not implemented")
}
func (UnimplementedConcernedServer) mustEmbedUnimplementedConcernedServer() {}
func (UnimplementedConcernedServer) testEmbeddedByValue()                   {}

// UnsafeConcernedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConcernedServer will
// result in compilation errors.
type UnsafeConcernedServer interface {
	mustEmbedUnimplementedConcernedServer()
}

func RegisterConcernedServer(s grpc.ServiceRegistrar, srv ConcernedServer) {
	// If the following call panics, it indicates UnimplementedConcernedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Concerned_ServiceDesc, srv)
}

func _Concerned_AddConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).AddConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_AddConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).AddConcerned(ctx, req.(*AddConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_CancelConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).CancelConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_CancelConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).CancelConcerned(ctx, req.(*CancelConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_IsConcerned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsConcernedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).IsConcerned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_IsConcerned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).IsConcerned(ctx, req.(*IsConcernedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_ConcernedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcernedListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).ConcernedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_ConcernedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).ConcernedList(ctx, req.(*ConcernedListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Concerned_ConcernedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcernedCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConcernedServer).ConcernedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Concerned_ConcernedCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConcernedServer).ConcernedCount(ctx, req.(*ConcernedCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Concerned_ServiceDesc is the grpc.ServiceDesc for Concerned service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Concerned_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Concerned",
	HandlerType: (*ConcernedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddConcerned",
			Handler:    _Concerned_AddConcerned_Handler,
		},
		{
			MethodName: "CancelConcerned",
			Handler:    _Concerned_CancelConcerned_Handler,
		},
		{
			MethodName: "IsConcerned",
			Handler:    _Concerned_IsConcerned_Handler,
		},
		{
			MethodName: "ConcernedList",
			Handler:    _Concerned_ConcernedList_Handler,
		},
		{
			MethodName: "ConcernedCount",
			Handler:    _Concerned_ConcernedCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}

const (
	Reply_CreateReply_FullMethodName    = "/social.Reply/CreateReply"
	Reply_DeleteReply_FullMethodName    = "/social.Reply/DeleteReply"
	Reply_ReplyDetail_FullMethodName    = "/social.Reply/ReplyDetail"
	Reply_ReplyList_FullMethodName      = "/social.Reply/ReplyList"
	Reply_ReplyCount_FullMethodName     = "/social.Reply/ReplyCount"
	Reply_AdminReplyList_FullMethodName = "/social.Reply/AdminReplyList"
)

// ReplyClient is the client API for Reply service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 评论服务 -----------------------------
type ReplyClient interface {
	CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error)
	DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error)
	ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error)
	ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error)
	ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error)
	AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error)
}

type replyClient struct {
	cc grpc.ClientConnInterface
}

func NewReplyClient(cc grpc.ClientConnInterface) ReplyClient {
	return &replyClient{cc}
}

func (c *replyClient) CreateReply(ctx context.Context, in *CreateReplyRequest, opts ...grpc.CallOption) (*CreateReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReplyResponse)
	err := c.cc.Invoke(ctx, Reply_CreateReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReplyResponse)
	err := c.cc.Invoke(ctx, Reply_DeleteReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) ReplyDetail(ctx context.Context, in *ReplyDetailRequest, opts ...grpc.CallOption) (*ReplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyDetailResponse)
	err := c.cc.Invoke(ctx, Reply_ReplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) ReplyList(ctx context.Context, in *ReplyListRequest, opts ...grpc.CallOption) (*ReplyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyListResponse)
	err := c.cc.Invoke(ctx, Reply_ReplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) ReplyCount(ctx context.Context, in *ReplyCountRequest, opts ...grpc.CallOption) (*ReplyCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyCountResponse)
	err := c.cc.Invoke(ctx, Reply_ReplyCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyClient) AdminReplyList(ctx context.Context, in *AdminReplyListRequest, opts ...grpc.CallOption) (*AdminReplyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminReplyListResponse)
	err := c.cc.Invoke(ctx, Reply_AdminReplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplyServer is the server API for Reply service.
// All implementations must embed UnimplementedReplyServer
// for forward compatibility.
//
// --------------------------- 评论服务 -----------------------------
type ReplyServer interface {
	CreateReply(context.Context, *CreateReplyRequest) (*CreateReplyResponse, error)
	DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyResponse, error)
	ReplyDetail(context.Context, *ReplyDetailRequest) (*ReplyDetailResponse, error)
	ReplyList(context.Context, *ReplyListRequest) (*ReplyListResponse, error)
	ReplyCount(context.Context, *ReplyCountRequest) (*ReplyCountResponse, error)
	AdminReplyList(context.Context, *AdminReplyListRequest) (*AdminReplyListResponse, error)
	mustEmbedUnimplementedReplyServer()
}

// UnimplementedReplyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplyServer struct{}

func (UnimplementedReplyServer) CreateReply(context.Context, *CreateReplyRequest) (*CreateReplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReply not implemented")
}
func (UnimplementedReplyServer) DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReply not implemented")
}
func (UnimplementedReplyServer) ReplyDetail(context.Context, *ReplyDetailRequest) (*ReplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyDetail not implemented")
}
func (UnimplementedReplyServer) ReplyList(context.Context, *ReplyListRequest) (*ReplyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyList not implemented")
}
func (UnimplementedReplyServer) ReplyCount(context.Context, *ReplyCountRequest) (*ReplyCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyCount not implemented")
}
func (UnimplementedReplyServer) AdminReplyList(context.Context, *AdminReplyListRequest) (*AdminReplyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminReplyList not implemented")
}
func (UnimplementedReplyServer) mustEmbedUnimplementedReplyServer() {}
func (UnimplementedReplyServer) testEmbeddedByValue()               {}

// UnsafeReplyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplyServer will
// result in compilation errors.
type UnsafeReplyServer interface {
	mustEmbedUnimplementedReplyServer()
}

func RegisterReplyServer(s grpc.ServiceRegistrar, srv ReplyServer) {
	// If the following call panics, it indicates UnimplementedReplyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reply_ServiceDesc, srv)
}

func _Reply_CreateReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).CreateReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_CreateReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).CreateReply(ctx, req.(*CreateReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_DeleteReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).DeleteReply(ctx, req.(*DeleteReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_ReplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).ReplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_ReplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).ReplyDetail(ctx, req.(*ReplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_ReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).ReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_ReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).ReplyList(ctx, req.(*ReplyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_ReplyCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).ReplyCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_ReplyCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).ReplyCount(ctx, req.(*ReplyCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reply_AdminReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminReplyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServer).AdminReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reply_AdminReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServer).AdminReplyList(ctx, req.(*AdminReplyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reply_ServiceDesc is the grpc.ServiceDesc for Reply service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reply_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Reply",
	HandlerType: (*ReplyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReply",
			Handler:    _Reply_CreateReply_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _Reply_DeleteReply_Handler,
		},
		{
			MethodName: "ReplyDetail",
			Handler:    _Reply_ReplyDetail_Handler,
		},
		{
			MethodName: "ReplyList",
			Handler:    _Reply_ReplyList_Handler,
		},
		{
			MethodName: "ReplyCount",
			Handler:    _Reply_ReplyCount_Handler,
		},
		{
			MethodName: "AdminReplyList",
			Handler:    _Reply_AdminReplyList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}

const (
	Message_NotificationList_FullMethodName   = "/social.Message/NotificationList"
	Message_UnreadCount_FullMethodName        = "/social.Message/UnreadCount"
	Message_MarkRead_FullMethodName           = "/social.Message/MarkRead"
	Message_MarkAllRead_FullMethodName        = "/social.Message/MarkAllRead"
	Message_DeleteNotification_FullMethodName = "/social.Message/DeleteNotification"
)

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 通知服务 -----------------------------
type MessageClient interface {
	NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error)
	UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*UnreadCountResponse, error)
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
	DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationListResponse)
	err := c.cc.Invoke(ctx, Message_NotificationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*UnreadCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnreadCountResponse)
	err := c.cc.Invoke(ctx, Message_UnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, Message_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResponse)
	err := c.cc.Invoke(ctx, Message_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNotificationResponse)
	err := c.cc.Invoke(ctx, Message_DeleteNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility.
//
// --------------------------- 通知服务 -----------------------------
type MessageServer interface {
	NotificationList(context.Context, *NotificationListRequest) (*NotificationListResponse, error)
	UnreadCount(context.Context, *UnreadCountRequest) (*UnreadCountResponse, error)
	MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error)
	DeleteNotification(context.Context, *DeleteNotificationRequest) (*DeleteNotificationResponse, error)
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServer struct{}

func (UnimplementedMessageServer) NotificationList(context.Context, *NotificationListRequest) (*NotificationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotificationList not implemented")
}
func (UnimplementedMessageServer) UnreadCount(context.Context, *UnreadCountRequest) (*UnreadCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnreadCount not implemented")
}
func (UnimplementedMessageServer) MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedMessageServer) MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedMessageServer) DeleteNotification(context.Context, *DeleteNotificationRequest) (*DeleteNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNotification not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}
func (UnimplementedMessageServer) testEmbeddedByValue()                 {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	// If the following call panics, it indicates UnimplementedMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_NotificationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).NotificationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_NotificationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).NotificationList(ctx, req.(*NotificationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_UnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).UnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_UnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).UnreadCount(ctx, req.(*UnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).MarkAllRead(ctx, req.(*MarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).DeleteNotification(ctx, req.(*DeleteNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotificationList",
			Handler:    _Message_NotificationList_Handler,
		},
		{
			MethodName: "UnreadCount",
			Handler:    _Message_UnreadCount_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _Message_MarkRead_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _Message_MarkAllRead_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _Message_DeleteNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}

const (
	Chat_SendMessage_FullMethodName   = "/social.Chat/SendMessage"
	Chat_Conversations_FullMethodName = "/social.Chat/Conversations"
	Chat_Messages_FullMethodName      = "/social.Chat/Messages"
	Chat_MarkRead_FullMethodName      = "/social.Chat/MarkRead"
	Chat_UnreadCount_FullMethodName   = "/social.Chat/UnreadCount"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 聊天服务 -----------------------------
type ChatClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	Conversations(ctx context.Context, in *ConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error)
	Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	MarkRead(ctx context.Context, in *ChatMarkReadRequest, opts ...grpc.CallOption) (*ChatMarkReadResponse, error)
	UnreadCount(ctx context.Context, in *ChatUnreadCountRequest, opts ...grpc.CallOption) (*ChatUnreadCountResponse, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Chat_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Conversations(ctx context.Context, in *ConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationsResponse)
	err := c.cc.Invoke(ctx, Chat_Conversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, Chat_Messages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) MarkRead(ctx context.Context, in *ChatMarkReadRequest, opts ...grpc.CallOption) (*ChatMarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMarkReadResponse)
	err := c.cc.Invoke(ctx, Chat_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) UnreadCount(ctx context.Context, in *ChatUnreadCountRequest, opts ...grpc.CallOption) (*ChatUnreadCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatUnreadCountResponse)
	err := c.cc.Invoke(ctx, Chat_UnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
//
// --------------------------- 聊天服务 -----------------------------
type ChatServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	Conversations(context.Context, *ConversationsRequest) (*ConversationsResponse, error)
	Messages(context.Context, *MessagesRequest) (*MessagesResponse, error)
	MarkRead(context.Context, *ChatMarkReadRequest) (*ChatMarkReadResponse, error)
	UnreadCount(context.Context, *ChatUnreadCountRequest) (*ChatUnreadCountResponse, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServer) Conversations(context.Context, *ConversationsRequest) (*ConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Conversations not implemented")
}
func (UnimplementedChatServer) Messages(context.Context, *MessagesRequest) (*MessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Messages not implemented")
}
func (UnimplementedChatServer) MarkRead(context.Context, *ChatMarkReadRequest) (*ChatMarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedChatServer) UnreadCount(context.Context, *ChatUnreadCountRequest) (*ChatUnreadCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnreadCount not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call panics, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Conversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Conversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_Conversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Conversations(ctx, req.(*ConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Messages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Messages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_Messages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Messages(ctx, req.(*MessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).MarkRead(ctx, req.(*ChatMarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_UnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatUnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).UnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_UnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).UnreadCount(ctx, req.(*ChatUnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Chat_SendMessage_Handler,
		},
		{
			MethodName: "Conversations",
			Handler:    _Chat_Conversations_Handler,
		},
		{
			MethodName: "Messages",
			Handler:    _Chat_Messages_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _Chat_MarkRead_Handler,
		},
		{
			MethodName: "UnreadCount",
			Handler:    _Chat_UnreadCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
