// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"rpc-social/internal/logic/concerned"
	"rpc-social/internal/svc"
	"rpc-social/social"
)

type ConcernedServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedConcernedServer
}

func NewConcernedServer(svcCtx *svc.ServiceContext) *ConcernedServer {
	return &ConcernedServer{
		svcCtx: svcCtx,
	}
}

func (s *ConcernedServer) AddConcerned(ctx context.Context, in *social.AddConcernedRequest) (*social.AddConcernedResponse, error) {
	l := concernedlogic.NewAddConcernedLogic(ctx, s.svcCtx)
	return l.AddConcerned(in)
}

func (s *ConcernedServer) CancelConcerned(ctx context.Context, in *social.CancelConcernedRequest) (*social.CancelConcernedResponse, error) {
	l := concernedlogic.NewCancelConcernedLogic(ctx, s.svcCtx)
	return l.CancelConcerned(in)
}

func (s *ConcernedServer) IsConcerned(ctx context.Context, in *social.IsConcernedRequest) (*social.IsConcernedResponse, error) {
	l := concernedlogic.NewIsConcernedLogic(ctx, s.svcCtx)
	return l.IsConcerned(in)
}

func (s *ConcernedServer) ConcernedList(ctx context.Context, in *social.ConcernedListRequest) (*social.ConcernedListResponse, error) {
	l := concernedlogic.NewConcernedListLogic(ctx, s.svcCtx)
	return l.ConcernedList(in)
}

func (s *ConcernedServer) ConcernedCount(ctx context.Context, in *social.ConcernedCountRequest) (*social.ConcernedCountResponse, error) {
	l := concernedlogic.NewConcernedCountLogic(ctx, s.svcCtx)
	return l.ConcernedCount(in)
}
